env:
    browser: true
    es6: true
    node: true
parserOptions:
    parser: '@typescript-eslint/parser'
    sourceType: module
extends:
    - 'plugin:vue/recommended'
    - '@vue/typescript'
globals:
    CKEDITOR: true
rules:
    # 不要提交console
    no-console: 2
    # 禁止在条件中使用常量表达式
    no-constant-condition: 2
    #  程序中不能出现debugger
    no-debugger: 2
    # 禁止将全局对象当作函数进行调用
    no-obj-calls: 2
    # 禁用未声明的变量，除非它们在 /global / 注释中被提到
    no-undef: 2
    # 禁止出现未使用过的变量
    no-unused-vars: 'off'
    # 要求或禁止末尾逗号
    comma-dangle:
        - 0
        - never
    # 禁止修改 const 声明的变量
    no-const-assign: 2
    # 禁止类成员中出现重复的名称
    no-dupe-class-members: 2
    # for循环趋势错误
    for-direction: 2
    # 禁止条件表达式中出现赋值操作符
    no-cond-assign: 2
    # 禁止 function 定义中出现重名参数
    no-dupe-args: 2
    # 禁止对象字面量中出现重复的 key
    no-dupe-keys: 2
    # 禁止出现重复的 case 标签
    no-duplicate-case: 2
    # 禁止出现空语句块
    no-empty: 2
    # 禁止对 function 声明重新赋值
    no-func-assign: 2
    # 禁止在嵌套的块中出现变量声明或 function 声明
    no-inner-declarations: 2
    # 禁止直接调用 Object.prototypes 的内置属性
    no-prototype-builtins: 2
    # 禁止出现令人困惑的多行表达式
    no-unexpected-multiline: 2
    # 禁止在return、throw、continue 和 break 语句之后出现不可达代码
    no-unreachable: 2
    # 禁止在 finally 语句块中出现控制流语句
    no-unsafe-finally: 2
    # 复杂逻辑判断添加括号
    no-unsafe-negation: 2
    # 要求使用 isNaN() 检查 NaN
    use-isnan: 2
    # 强制 typeof 表达式与有效的字符串进行比较
    valid-typeof: 2
    # 强制把变量的使用限制在其定义的作用域范围内
    block-scoped-var: 2
    # 语句括号缺失警告
    curly: 1
    # 禁用 arguments.caller 或 arguments.callee
    no-caller: 2
    # 不允许在 case 子句中使用词法声明
    no-case-declarations: 2
    # 禁止使用空解构模式
    no-empty-pattern: 2
    # 禁用 eval()
    no-eval: 2
    # 禁止扩展原生类型
    no-extend-native: 2
    # 禁止不必要的 .bind() 调用
    no-extra-bind: 2
    # 禁止数字字面量中使用前导和末尾小数点
    no-floating-decimal: 2
    # 禁止修改原生对象
    no-global-assign: 2
    # 禁止使用类似 eval() 的方法
    no-implied-eval: 2
    # 禁用标签语句
    no-labels: 2
    # 禁用不必要的嵌套块
    no-lone-blocks: 2
    # 禁止在循环中出现 function 声明和表达式
    no-loop-func: 0
    # 禁止使用多行字符串
    no-multi-str: 2
    # 禁止直接调用 Object.prototypes 的内置属性
    no-proto: 2
    # 禁止多次声明同一变量
    no-redeclare: 2
    # 禁止在 return 语句中使用赋值语句
    no-return-assign: 2
    # 禁止使用 javascript: url
    no-script-url: 2
    # 禁止自我赋值
    no-self-assign: 2
    # 禁止自身比较
    no-self-compare: 2
    # 禁止使用with
    no-with: 2
    # 要求 IIFE 使用括号括起来
    wrap-iife: 2
    # 禁止修改类声明的变量
    no-class-assign: 2
    # 禁用特定的全局变量
    no-restricted-globals: 2
    # 禁止变量声明与外层作用域的变量同名
    no-shadow: 1
    # 禁止将标识符定义为受限的名字
    no-shadow-restricted-names: 2

    # 以下是Typescript相关的设置
    # 禁止使用Any
    no-explicit-any: 0
    # 强制驼峰命名
    '@typescript-eslint/camelcase': 0

    # 以下是 eslint-plugin-vue 插件的配置覆盖（plugin:vue/recommended），参考：https://vuejs.github.io/eslint-plugin-vue/
    # 强制每行html标签里的最大属性数
    vue/max-attributes-per-line: 0
    # 在template里面的html标签必须使用自闭合方式
    vue/html-self-closing: 0
    # 禁止解析<template>中的错误
    vue/no-parsing-error:
        - 2
        - x-invalid-end-tag: false
    # props属性命名强制使用驼峰式
    vue/attribute-hyphenation:
        - 2
        - never
    vue/singleline-html-element-content-newline: off
    # vue/html-indent:
    #     - 2
    #     - tab
    #     - attribute: 1
    #     - baseIndent: 1
    #     - closeBracket: 0,
    #     - alignAttributesVertically: true
    #     - ignores: []
    vue/order-in-components:
        - error
        - order:
              - name
              - parent
              - el
              - mixins
              - functional
              - - delimiters
                - comments
              - - components
                - directives
                - filters
              - extends
              - inheritAttrs
              - model
              - i18n
              - - props
                - propsData
              - data
              - computed
              - methods
              - watch
              - LIFECYCLE_HOOKS
              - - template
                - render
              - renderError
root: true
